name: addb

channels:
  - conda-forge
  - bioconda
  - nodefaults

dependencies:
  # NodeJS EOL: 2022-04-30
  - nodejs=12
  - pigz
  - pygraphviz
  - mysqlclient
  - r-base=3.6
  - r-ggiraph
  - r-knitr
  - r-ggplot2
  - r-htmlwidgets
  - r-pbmcapply
  - r-ggseqlogo
  - r-svglite
  # required for ggplot2
  - r-rlang
  - r-lazyeval
  # needed to install rmimp from source:
  - r-rocr
  - r-data.table
  - r-mclust
  - bioconductor-s4vectors
  - bioconductor-genomicranges
  - bioconductor-biostrings
  - bioconductor-biocgenerics
  - pip
  - pip:
    - wheel
    - -r website/requirements.txt
    - -r website/tests/requirements.txt
    - -r website/analyses/requirements.txt
