from collections import defaultdict

from database import db
from database_testing import DatabaseTest
from imports.sites.infections import EnterovirusPhosphoImporter
from miscellaneous import make_named_gz_file, make_named_temp_file
from models import Protein, Site, RegulatorySiteAssociation


MAPPINGS = """\
A0AVK6	RefSeq_NT	NM_001256371.1
A0AVK6	RefSeq_NT	NM_001256372.1
A0AVK6	RefSeq_NT	NM_024680.3
A5YM69	RefSeq_NT	NM_001003702.2
A5YM69	RefSeq_NT	XM_017030457.1
Q12774-1	RefSeq_NT	NM_005435.3
"""


CANONICAL = """\
>sp|A0AVK6|E2F8_HUMAN Transcription factor E2F8 OS=Homo sapiens OX=9606 GN=E2F8 PE=1 SV=1
MENEKENLFCEPHKRGLMKTPLKESTTANIVLAEIQPDFGPLTTPTKPKEGSQGEPWTPT
ANLKMLISAVSPEIRNRDQKRGLFDNRSGLPEAKDCIHEHLSGDEFEKSQPSRKEKSLGL
LCHKFLARYPNYPNPAVNNDICLDEVAEELNVERRRIYDIVNVLESLHMVSRLAKNRYTW
HGRHNLNKTLGTLKSIGEENKYAEQIMMIKKKEYEQEFDFIKSYSIEDHIIKSNTGPNGH
PDMCFVELPGVEFRAASVNSRKDKSLRVMSQKFVMLFLVSTPQIVSLEVAAKILIGEDHV
EDLDKSKFKTKIRRLYDIANVLSSLDLIKKVHVTEERGRKPAFKWTGPEISPNTSGSSPV
IHFTPSDLEVRRSSKENCAKNLFSTRGKPNFTRHPSLIKLVKSIESDRRKINSAPSSPIK
TNKAESSQNSAPFPSKMAQLAAICKMQLEEQSSESRQKVKVQLARSGPCKPVAPLDPPVN
AEMELTAPSLIQPLGMVPLIPSPLSSAVPLILPQAPSGPSYAIYLQPTQAHQSVTPPQGL
>sp|A5YM69|ARG35_HUMAN Rho guanine nucleotide exchange factor 35 OS=Homo sapiens OX=9606 GN=ARHGEF35 PE=1 SV=1
MEAEEAQHGASPPISAIEEFSIIPEAPMRSSQVSALGLEAQEDEDPSYKWREEHRLSATQ
QSELRDVCDYAIETMPSFPKEGSADVEPNQESLVAEACDTPEHWEAVPQSLAGRQARTLA
PPELWACPIQSEHLDMAPFSSDLGSEEEEVEFWPGLTSLTLGSGQAEEEEETSSDNSGQT
RYYSPCEEHPAETNQNEGAESGTIRQGEELPSEELQESQGLLHPQEVQVLEEQGQQEAGF
RGEGTLREDVCADGLLGEEQMIEQVNDEKGEQKQKQEQVQDVMLGRQGERMGLTGEPEGL
NDGEWEQEDMERKAQGQGGPEQGEERKRELQVPEENRADSQDEKSQTFLGKSEEVTGKQE
DHGIKEKGVPVSGQEAKEPESWDGGRLGAVGRARSREEENEHHGPSMPALIAPEDSPHCD
LFPGASYLVTQIPGTQTESRAEELSPAALSPLLEPIRCSHQPISLLGSFLTEESPDKEKL
>sp|Q12774|ARHG5_HUMAN Rho guanine nucleotide exchange factor 5 OS=Homo sapiens OX=9606 GN=ARHGEF5 PE=1 SV=3
MEAEEAQRGASPPISAIEEFSIIPEAPMRSSQVSALGLEAQEDEDPSYKWREEHRLSATQ
QSELRDVCDYAIETMPSFPKEGSADVEPNQESLVAEACDTPEHWEAVPQSLAGRQARTLA
PPELWACPIQSEHLDMAPFSSDLGSEEEEVEFWPGLTSLTLGSGQAEEEEETSSDNSGQT
RYYSPCEEHPAETNQNEGSESGTIRQGEELPPEELQESQGLLHPQEVQVLEEQGQQEAGF
RGEGTLREDVCADGLLGEEQMIEQVNDEKGEQKQKQEQVQDVMLGRQGERMGLTGEPEGL
NDGEWEQEDMERKAQGQGGPEQGEERKRELQVPEENRADSQDEKSQTFLGKSEEVTGKQE
DHGIKEKGVPVSGQEAKEPESWDGGRLGAVGRARSREEENEHHGPSMPALIAPEDSPHCD
"""

ALTERNATIVE = ''

SITES = """\
Proteins	Positions within proteins	Amino acid	Welch's T-test q-value Mock_10h_CT	Welch's T-test q-value 10h_CT	Log2 10h_CT
A0AVK6	417	S	0.485383076281784	0.0121122103266025	-1.7216787499999997
A0AVK6	68	S	0.72101435190417	1.0	0.13898449999999984
A5YM69;Q12774	340;340	S	0.87691443630075	0.000455223880597015	4.38717325
"""


class TestImport(DatabaseTest):

    def test_import(self):
        protein_a0avk6 = Protein(
            refseq='NM_001256372',
            sequence='MENEKENLFCEPHKRGLMKTPLKESTTANIVLAEIQPDFGPLTTPTKPKEGSQGEPWTPTANLKMLISAVSPEIRNRDQKRGLFDNRSGLPEAKDCIHEHLSGDEFEKSQPSRKEKSLGLLCHKFLARYPNYPNPAVNNDICLDEVAEELNVERRRIYDIVNVLESLHMVSRLAKNRYTWHGRHNLNKTLGTLKSIGEENKYAEQIMMIKKKEYEQEFDFIKSYSIEDHIIKSNTGPNGHPDMCFVELPGVEFRAASVNSRKDKSLRVMSQKFVMLFLVSTPQIVSLEVAAKILIGEDHVEDLDKSKFKTKIRRLYDIANVLSSLDLIKKVHVTEERGRKPAFKWTGPEISPNTSGSSPVIHFTPSDLEVRRSSKENCAKNLFSTRGKPNFTRHPSLIKLVKSIESDRRKINSAPSSPIKTNKAESSQNSAPFPSKMAQLAAICKMQLEEQSSESRQKVKVQLARSGPCKPVAPLDPPVNAEMELTAPSLIQPLGMVPLIPSPLSSAVPLILPQAPSGPSYAIYLQPTQAHQSVTPPQGL'
        )
        protein_a5ym69 = Protein(
            refseq='NM_001003702',
            sequence='MEAEEAQHGASPPISAIEEFSIIPEAPMRSSQVSALGLEAQEDEDPSYKWREEHRLSATQQSELRDVCDYAIETMPSFPKEGSADVEPNQESLVAEACDTPEHWEAVPQSLAGRQARTLAPPELWACPIQSEHLDMAPFSSDLGSEEEEVEFWPGLTSLTLGSGQAEEEEETSSDNSGQTRYYSPCEEHPAETNQNEGAESGTIRQGEELPSEELQESQGLLHPQEVQVLEEQGQQEAGFRGEGTLREDVCADGLLGEEQMIEQVNDEKGEQKQKQEQVQDVMLGRQGERMGLTGEPEGLNDGEWEQEDMERKAQGQGGPEQGEERKRELQVPEENRADSQDEKSQTFLGKSEEVTGKQEDHGIKEKGVPVSGQEAKEPESWDGGRLGAVGRARSREEENEHHGPSMPALIAPEDSPHCDLFPGASYLVTQIPGTQTESRAEELSPAALSPLLEPIRCSHQPISLLGSFLTEESPDKEKL'
        )
        protein_q12774 = Protein(
            refseq='NM_005435',
            sequence='MEAEEAQRGASPPISAIEEFSIIPEAPMRSSQVSALGLEAQEDEDPSYKWREEHRLSATQQSELRDVCDYAIETMPSFPKEGSADVEPNQESLVAEACDTPEHWEAVPQSLAGRQARTLAPPELWACPIQSEHLDMAPFSSDLGSEEEEVEFWPGLTSLTLGSGQAEEEEETSSDNSGQTRYYSPCEEHPAETNQNEGSESGTIRQGEELPPEELQESQGLLHPQEVQVLEEQGQQEAGFRGEGTLREDVCADGLLGEEQMIEQVNDEKGEQKQKQEQVQDVMLGRQGERMGLTGEPEGLNDGEWEQEDMERKAQGQGGPEQGEERKRELQVPEENRADSQDEKSQTFLGKSEEVTGKQEDHGIKEKGVPVSGQEAKEPESWDGGRLGAVGRARSREEENEHHGPSMPALIAPEDSPHCD'
        )

        db.session.add_all([
            protein_a0avk6,
            protein_a5ym69,
            protein_q12774
        ])

        importer = EnterovirusPhosphoImporter(
            make_named_gz_file(CANONICAL),
            make_named_gz_file(ALTERNATIVE),
            make_named_gz_file(MAPPINGS)
        )

        sites = importer.load_sites(make_named_temp_file(SITES, suffix='.tsv'))

        assert len(sites) == 3

        db.session.add_all(sites)
        db.session.commit()

        associations = RegulatorySiteAssociation.query.all()
        assert len(associations) == 3

        sites = Site.query.all()

        sites_by_protein = defaultdict(list)
        for site in sites:
            sites_by_protein[site.protein.refseq].append(site)
        assert len(sites_by_protein) == 3

        assert set(sites_by_protein.keys()) == {
            protein_a0avk6.refseq,
            protein_a5ym69.refseq,
            protein_q12774.refseq
        }

        a0avk6_sites = {
            site.position: site
            for site in sites_by_protein['NM_001256372']
        }
        # only one site meets the q-value threshold
        assert len(a0avk6_sites) == 1

        site = a0avk6_sites[417]

        assert site.residue == 'S'
        assert site.types_names == {'phosphorylation (enterovirus)'}

        assert len(site.associations) == 1
        association: RegulatorySiteAssociation = next(iter(site.associations))
        assert association.event.name == 'CVB3 enterovirus infection'

        assert association.adjusted_p_value == 0.0121122103266025
        assert association.finite_effect_size == -1.7216787499999997
        assert association.infinite_effect_size is None
        assert association.effect_size == -1.7216787499999997
        assert association.effect_size_type == 'log2FC'
        assert association.site_type.name == 'phosphorylation (enterovirus)'
