from collections import defaultdict

from database import db
from database_testing import DatabaseTest
from imports.sites.covid import CovidPhosphoImporter
from miscellaneous import make_named_gz_file, make_named_temp_file
from models import Protein, Site, RegulatorySiteAssociation

MAPPINGS = """\
Q9NRG9-2	RefSeq_NT	NM_001173466.1
Q9NRG9-1	RefSeq_NT	NM_015665.5
Q6PD74-2	RefSeq_NT	NM_001271885.1
Q6PD74-2	RefSeq_NT	NM_001271886.1
Q6PD74-1	RefSeq_NT	NM_024666.4
Q15942-1	RefSeq_NT	NM_001010972.1
Q15942-1	RefSeq_NT	NM_003461.4
Q8TBC5-3	RefSeq_NT	NM_001145542.1
Q8TBC5-1	RefSeq_NT	NM_001145543.1
Q8TBC5-4	RefSeq_NT	NM_001145544.1
Q8TBC5-1	RefSeq_NT	NM_023926.4
Q8TBC5-1	RefSeq_NT	XM_005259174.4
Q8TBC5-1	RefSeq_NT	XM_006723335.2
Q8TBC5-1	RefSeq_NT	XM_011527238.1
Q8TBC5-1	RefSeq_NT	XM_011527239.2
Q8TBC5-2	RefSeq_NT	XM_017027169.1
Q8TBC5-2	RefSeq_NT	XM_017027170.1
Q8TBC5-2	RefSeq_NT	XM_017027171.1
"""


CANONICAL = """\
>sp|Q9NRG9|AAAS_HUMAN Aladin OS=Homo sapiens OX=9606 GN=AAAS PE=1 SV=1
MCSLGLFPPPPPRGQVTLYEHNNELVTGSSYESPPPDFRGQWINLPVLQLTKDPLKTPGR
LDHGTRTAFIHHREQVWKRCINIWRDVGLFGVLNEIANSEEEVFEWVKTASGWALALCRW
ASSLHGSLFPHLSLRSEDLIAEFAQVTNWSSCCLRVFAWHPHTNKFAVALLDDSVRVYNA
SSTIVPSLKHRLQRNVASLAWKPLSASVLAVACQSCILIWTLDPTSLSTRPSSGCAQVLS
HPGHTPVTSLAWAPSGGRLLSASPVDAAIRVWDVSTETCVPLPWFRGGGVTNLLWSPDGS
KILATTPSAVFRVWEAQMWTCERWPTLSGRCQTGCWSPDGSRLLFTVLGEPLIYSLSFPE
RCGEGKGCVGGAKSATIVADLSETTIQTPDGEERLGGEAHSMVWDPSGERLAVLMKGKPR
VQDGKPVILLFRTRNSPVFELLPCGIIQGEPGAQPQLITFHPSFNKGALLSVGWSTGRIA
HIPLYFVNAQFPRFSPVLGRAQEPPAGGGGSIHDLPLFTETSPTSAPWDPLPGPPPVLPH
SPHSHL
>sp|Q6PD74|AAGAB_HUMAN Alpha- and gamma-adaptin-binding protein p34 OS=Homo sapiens OX=9606 GN=AAGAB PE=1 SV=1
MAAGVPCALVTSCSSVFSGDQLVQHILGTEDLIVEVTSNDAVRFYPWTIDNKYYSADINL
CVVPNKFLVTAEIAESVQAFVVYFDSTQKSGLDSVSSWLPLAKAWLPEVMILVCDRVSED
GINRQKAQEWCIKHGFELVELSPEELPEEDDDFPESTGVKRIVQALNANVWSNVVMKNDR
NQGFSLLNSLTGTNHSIGSADPCHPEQPHLPAADSTESLSDHRGGASNTTDAQVDSIVDP
MLDLDIQELASLTTGGGDVENFERLFSKLKEMKDKAATLPHEQRKVHAEKVAKAFWMAIG
GDRDEIEGLSSDEEH
>sp|Q15942|ZYX_HUMAN Zyxin OS=Homo sapiens OX=9606 GN=ZYX PE=1 SV=1
MAAPRPSPAISVSVSAPAFYAPQKKFGPVVAPKPKVNPFRPGDSEPPPAPGAQRAQMGRV
GEIPPPPPEDFPLPPPPLAGDGDDAEGALGGAFPPPPPPIEESFPPAPLEEEIFPSPPPP
PEEEGGPEAPIPPPPQPREKVSSIDLEIDSLSSLLDDMTKNDPFKARVSSGYVPPPVATP
FSSKSSTKPAAGGTAPLPPWKSPSSSQPLPQVPAPAQSQTQFHVQPQPQPKPQVQLHVQS
QTQPVSLANTQPRGPPASSPAPAPKFSPVTPKFTPVASKFSPGAPGGSGSQPNQKLGHPE
ALSAGTGSPQPPSFTYAQQREKPRVQEKQHPVPPPAQNQNQVRSPGAPGPLTLKEVEELE
QLTQQLMQDMEHPQRQNVAVNELCGRCHQPLARAQPAVRALGQLFHIACFTCHQCAQQLQ
GQQFYSLEGAPYCEGCYTDTLEKCNTCGEPITDRMLRATGKAYHPHCFTCVVCARPLEGT
SFIVDQANRPHCVPDYHKQYAPRCSVCSEPIMPEPGRDETVRVVALDKNFHMKCYKCEDC
GKPLSIEADDNGCFPLDGHVLCRKCHTARAQT
>sp|Q8TBC5|ZSC18_HUMAN Zinc finger and SCAN domain-containing protein 18 OS=Homo sapiens OX=9606 GN=ZSCAN18 PE=1 SV=2
MLPLEKAFASPRSSPAPPDLPTPGSAAGVQQEEPETIPERTPADLEFSRLRFREFVYQEA
AGPHQTLARLHELCRQWLMPEARSKEQMLELLVLEQFLGILPDKVRPWVVAQYPESCKKA
ASLVEGLADVLEEPGMLLGSPAGSSSILSDGVYERHMDPLLLPGELASPSQALGAGEIPA
PSETPWLSPDPLFLEQRRVREAKTEEDGPANTEQKLKSFPEDPQHLGEWGHLDPAEENLK
SYRKLLLWGYQLSQPDAASRLDTEELRLVERDPQGSSLPEGGRRQESAGCACEEAAPAGV
LPELPTEAPPGDALADPPSGTTEEEEEQPGKAPDPQDPQDAESDSATGSQRQSVIQQPAP
DRGTAKLGTKRPHPEDGDGQSLEGVSSSGDSAGLEAGQGPGADEPGLSRGKPYACGECGE
AFAWLSHLMEHHSSHGGRKRYACQGCWKTFHFSLALAEHQKTHEKEKSYALGGARGPQPS
TREAQAGARAGGPPESVEGEAPPAPPEAQR
"""

ALTERNATIVE = ''

SITES = """\
Gene_Name	uniprot	site	Inf_24Hr.log2FC	Ctrl_24Hr.adj.pvalue	Inf_24Hr.adj.pvalue
AAAS	Q9NRG9	S495	-0.25	0.84	0.79
AAGAB	Q6PD74	S310	0.07	0.99	0.95
ZYX	Q15942	S308	-3.95	0.066	0.00011
ZYX	Q15942	S7	-Inf	0.066	0.0
ZSCAN18	Q8TBC5	G208	1.51	0.35	0.0031
"""


class TestImport(DatabaseTest):

    def test_import(self):
        protein_aagab = Protein(
            refseq='NM_024666',
            sequence='MAAGVPCALVTSCSSVFSGDQLVQHILGTEDLIVEVTSNDAVRFYPWTIDNKYYSADINLCVVPNKFLVTAEIAESVQAFVVYFDSTQKSGLDSVSSWLPLAKAWLPEVMILVCDRVSEDGINRQKAQEWCIKHGFELVELSPEELPEEDDDFPESTGVKRIVQALNANVWSNVVMKNDRNQGFSLLNSLTGTNHSIGSADPCHPEQPHLPAADSTESLSDHRGGASNTTDAQVDSIVDPMLDLDIQELASLTTGGGDVENFERLFSKLKEMKDKAATLPHEQRKVHAEKVAKAFWMAIGGDRDEIEGLSSDEEH'
        )
        protein_zyx = Protein(
            refseq='NM_003461',
            sequence='MAAPRPSPAISVSVSAPAFYAPQKKFGPVVAPKPKVNPFRPGDSEPPPAPGAQRAQMGRVGEIPPPPPEDFPLPPPPLAGDGDDAEGALGGAFPPPPPPIEESFPPAPLEEEIFPSPPPPPEEEGGPEAPIPPPPQPREKVSSIDLEIDSLSSLLDDMTKNDPFKARVSSGYVPPPVATPFSSKSSTKPAAGGTAPLPPWKSPSSSQPLPQVPAPAQSQTQFHVQPQPQPKPQVQLHVQSQTQPVSLANTQPRGPPASSPAPAPKFSPVTPKFTPVASKFSPGAPGGSGSQPNQKLGHPEALSAGTGSPQPPSFTYAQQREKPRVQEKQHPVPPPAQNQNQVRSPGAPGPLTLKEVEELEQLTQQLMQDMEHPQRQNVAVNELCGRCHQPLARAQPAVRALGQLFHIACFTCHQCAQQLQGQQFYSLEGAPYCEGCYTDTLEKCNTCGEPITDRMLRATGKAYHPHCFTCVVCARPLEGTSFIVDQANRPHCVPDYHKQYAPRCSVCSEPIMPEPGRDETVRVVALDKNFHMKCYKCEDC GKPLSIEADDNGCFPLDGHVLCRKCHTARAQT'
        )
        protein_zyx_alt = Protein(
            refseq='NM_001010972',
            sequence='MAAPRPSPAISVSVSAPAFYAPQKKFGPVVAPKPKVNPFRPGDSEPPPAPGAQRAQMGRVGEIPPPPPEDFPLPPPPLAGDGDDAEGALGGAFPPPPPPIEESFPPAPLEEEIFPSPPPPPEEEGGPEAPIPPPPQPREKVSSIDLEIDSLSSLLDDMTKNDPFKARVSSGYVPPPVATPFSSKSSTKPAAGGTAPLPPWKSPSSSQPLPQVPAPAQSQTQFHVQPQPQPKPQVQLHVQSQTQPVSLANTQPRGPPASSPAPAPKFSPVTPKFTPVASKFSPGAPGGSGSQPNQKLGHPEALSAGTGSPQPPSFTYAQQREKPRVQEKQHPVPPPAQNQNQVRSPGAPGPLTLKEVEELEQLTQQLMQDMEHPQRQNVAVNELCGRCHQPLARAQPAVRALGQLFHIACFTCHQCAQQLQGQQFYSLEGAPYCEGCYTDTLEKCNTCGEPITDRMLRATGKAYHPHCFTCVVCARPLEGTSFIVDQANRPHCVPDYHKQYAPRCSVCSEPIMPEPGRDETVRVVALDKNFHMKCYKCEDC GKPLSIEADDNGCFPLDGHVLCRKCHTARAQT'
        )
        protein_zscan = Protein(
            refseq = 'NM_023926',
            sequence='MLPLEKAFASPRSSPAPPDLPTPGSAAGVQQEEPETIPERTPADLEFSRLRFREFVYQEAAGPHQTLARLHELCRQWLMPEARSKEQMLELLVLEQFLGILPDKVRPWVVAQYPESCKKAASLVEGLADVLEEPGMLLGSPAGSSSILSDGVYERHMDPLLLPGELASPSQALGAGEIPAPSETPWLSPDPLFLEQRRVREAKTEEDGPANTEQKLKSFPEDPQHLGEWGHLDPAEENLKSYRKLLLWGYQLSQPDAASRLDTEELRLVERDPQGSSLPEGGRRQESAGCACEEAAPAGVLPELPTEAPPGDALADPPSGTTEEEEEQPGKAPDPQDPQDAESDSATGSQRQSVIQQPAPDRGTAKLGTKRPHPEDGDGQSLEGVSSSGDSAGLEAGQGPGADEPGLSRGKPYACGECGEAFAWLSHLMEHHSSHGGRKRYACQGCWKTFHFSLALAEHQKTHEKEKSYALGGARGPQPSTREAQAGARAGGPPESVEGEAPPAPPEAQR'
        )

        db.session.add_all([
            protein_aagab,
            protein_zyx,
            protein_zyx_alt,
            protein_zscan
        ])

        importer = CovidPhosphoImporter(
            make_named_gz_file(CANONICAL),
            make_named_gz_file(ALTERNATIVE),
            make_named_gz_file(MAPPINGS)
        )

        sites = importer.load_sites(make_named_temp_file(SITES, suffix='.tsv'))

        assert len(sites) == 4

        db.session.add_all(sites)
        db.session.commit()

        sites = Site.query.all()

        sites_by_protein = defaultdict(list)
        for site in sites:
            sites_by_protein[site.protein.refseq].append(site)
        assert len(sites_by_protein) == 2

        assert set(sites_by_protein.keys()) == {protein_zyx.refseq, protein_zyx_alt.refseq}

        zyx_sites = {
            site.position: site
            for site in sites_by_protein['NM_003461']
        }
        assert len(zyx_sites) == 2

        site = zyx_sites[308]

        assert site.residue == 'S'
        assert site.types_names == {'phosphorylation (SARS-CoV-2)'}

        assert len(site.associations) == 2
        association: RegulatorySiteAssociation = next(iter(site.associations))
        assert association.event.name == 'SARS-CoV-2 infection'

        assert association.adjusted_p_value == 0.00011
        assert association.finite_effect_size == -3.95
        assert association.infinite_effect_size is None
        assert association.effect_size == -3.95
        assert association.effect_size_type == 'log2FC'
        assert association.site_type.name == 'phosphorylation (SARS-CoV-2)'

        inf_site = zyx_sites[7]
        inf_association = list(inf_site.associations)[0]
        assert inf_association.finite_effect_size is None
        assert inf_association.infinite_effect_size == -1
        assert inf_association.effect_size == float('-inf')
