SQLALCHEMY_DATABASE_URI = 'mysql://user:pass@localhost/db'
SQLALCHEMY_TRACK_MODIFICATIONS = True
SECRET_KEY = 'replace_this'
DEBUG = True
DEFAULT_HOST = '0.0.0.0'    # use public IPs
DEFAULT_PORT = 5000
JSONIFY_PRETTYPRINT_REGULAR = False
